management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: boot
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    initialization-mode: always